# the boolean value only sport "false | true"
# "True", "False", "0", "1" and others all would be false
[default]
default_username = unnamed

[style]
system_name = SYSTEM
system_msg_prompt = $
normal_msg_prompt = #

[functions]
enable_log_debug = false