# 打印当前正在执行的源代码目录
message(STATUS "CMAKE_CURRENT_SOURCE_DIR: " ${CMAKE_CURRENT_SOURCE_DIR})

# 打印当前正在执行的CMake脚本的完整名称
message(STATUS "CMAKE_CURRENT_LIST_FILE" ${CMAKE_CURRENT_LIST_FILE})
message(STATUS "CMAKE_CURRENT_LIST_DIR" ${CMAKE_CURRENT_LIST_DIR})

